const pedido = 'Olhe a foto deste comprovante e responda em UMA linha, sem escrever mais nada, com 2 pedaços separados por |. Primeiro pedaço: o emoji da categoria, o nome do estabelecimento dentro de <strong>, e depois cada item comprado com seu valor, um por linha usando <br>. Segundo pedaço: o total pago, só o número, com ponto e sempre com duas casas decimais. As categorias são: 🛒 Mercado, 🚗 Transporte, 🍔 Comida, 💊 Saúde, 🎉 Lazer, 🏠 Casa, 💸 Outros. Exemplo: 🍔 <strong>Padaria Pão Quente</strong><br>Pão — R$ 5,00<br>Leite — R$ 4,50|9.50';
let total = 0, quantidade = 0, stream = null;
let abrirCameraBtn, tirarFotoBtn, fecharCameraBtn, videoElement, canvasElement, statusElement;

document.addEventListener('DOMContentLoaded', () => {
    abrirCameraBtn = document.getElementById('abrirCamera'); tirarFotoBtn = document.getElementById('tirarFoto'); fecharCameraBtn = document.getElementById('fecharCamera'); videoElement = document.getElementById('video'); canvasElement = document.getElementById('canvas'); statusElement = document.getElementById('statusProcessamento');
    abrirCameraBtn.addEventListener('click', abrirCameraFunction); tirarFotoBtn.addEventListener('click', tirarFotoFunction); fecharCameraBtn.addEventListener('click', fecharCamera);
});
async function abrirCameraFunction() { try { stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); videoElement.srcObject = stream; videoElement.style.display = 'block'; abrirCameraBtn.hidden = true; tirarFotoBtn.hidden = false; fecharCameraBtn.hidden = false; } catch (erro) { alert('Não foi possível acessar a câmera: ' + erro.message); } }
async function tirarFotoFunction() { if (!videoElement.videoWidth) return; canvasElement.width = videoElement.videoWidth; canvasElement.height = videoElement.videoHeight; canvasElement.getContext('2d').drawImage(videoElement, 0, 0); canvasElement.toBlob(async blob => { if (!blob) return; fecharCamera(); await processarFoto(new File([blob], 'foto.jpg', { type: 'image/jpeg' })); }, 'image/jpeg', .95); }
function fecharCamera() { if (stream) { stream.getTracks().forEach(track => track.stop()); stream = null; } videoElement.style.display = 'none'; videoElement.srcObject = null; abrirCameraBtn.hidden = false; tirarFotoBtn.hidden = true; fecharCameraBtn.hidden = true; }
function atualizarResumo() { document.querySelector('.total-gasto').textContent = `R$ ${total.toFixed(2).replace('.', ',')}`; document.querySelector('.resumo-total').textContent = `R$ ${total.toFixed(2).replace('.', ',')}`; document.querySelector('.resumo-quantidade').textContent = quantidade; document.querySelector('.comprovantes-lidos').textContent = quantidade === 1 ? '1 comprovante lido' : `${quantidade} comprovantes lidos`; }
async function processarFoto(arquivo) { try { statusElement.hidden = false; statusElement.textContent = '🤖 A IA está lendo seu comprovante…'; const resposta = await puter.ai.chat(pedido, arquivo); const [itens, valorTexto] = resposta.message.content.trim().split('|'); const valor = Number(valorTexto); if (!itens || !Number.isFinite(valor)) throw new Error('A IA respondeu em um formato inesperado.'); document.querySelector('.empty-state')?.remove(); document.querySelector('.lista').insertAdjacentHTML('afterbegin', `<article class="comprovante"><div class="itens">${itens}</div><div class="separador"></div><div class="total-nota">Total da nota: R$ ${valor.toFixed(2).replace('.', ',')}</div></article>`); total += valor; quantidade += 1; atualizarResumo(); statusElement.textContent = '✓ Comprovante adicionado ao resumo.'; } catch (erro) { console.error(erro); statusElement.textContent = 'Não foi possível ler esse comprovante.'; alert('Erro ao processar a foto: ' + erro.message); } }
window.addEventListener('beforeunload', fecharCamera);